"""empty message

Revision ID: 4c2dc57d91b1
Revises: a5cffa318ac2
Create Date: 2026-01-16 00:18:53.022674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2dc57d91b1'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('archivo_jpg', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seguido_id', sa.Integer(), nullable=False),
    sa.Column('seguidor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seguido_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['seguidor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=False),
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_post'], ['post.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('le_gusta_usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['le_gusta_usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likear')
    op.drop_table('comentar')
    op.drop_table('seguir')
    op.drop_table('post')
    op.drop_table('usuario')
    # ### end Alembic commands ###
